vt = {
    "role": "1",
    "role_name": "Vanilla Villager",
    "faction": "",
    "bpv_status": 0,
    "ninja": 0,
    "x_shot_limit": 0,
    "strongman": 0,
    "even_night": 0,
    "odd_night": 0,
    "godfather": 0,
    "backup": 0,
    "night_x": 0,
    "macho": 0,
    "recluse": 0,
    "lost": 0,
    "vengeful": 0,
    "flipless": 0,
    "vote_weight": 0,
    "hide_vote_weight": 0,
    "non_consecutive": 0,
    "self_targetable": 0,
    "treestump": 0,
    "neighbor": 0,
    "mason": 0,
    "lover": 0,
    "loyal": 0,
    "disloyal": 0,
    "uncooperative": 0,
    "vendor_items": "",
    "joat": 0,
    "inventor": 0,
    "powers": {
        "alignment inspection": 0,
        "fullcop": 0,
        "rolecop": 0,
        "bodyguard": 0,
        "protection": 0,
        "frame": 0,
        "jail": 0,
        "roleblock": 0,
        "track": 0,
        "watch": 0,
        "motion detect": 0,
        "voyeur": 0,
        "kill": 0,
        "daykill": 0,
        "poison": 0,
        "bpv": 0
    },
    "ita_count": 0,
    "ita_base_hit": 0,
    "ita_immunity": 0,
    "ita_vulnerability": 0,
    "ita_shield_status": 0,
    "ita_booster": 0,
    "ita_nerfer": 0,
    "character_name": "Van Chilla",
    "character_image": "https://c.tenor.com/tc_6iH63G6cAAAAd/tany.gif",
    "alignment": "village",
    "faction_color": "#339933"
}
goon = {
    "role": "2",
    "role_name": "Wolf",
    "faction": "Wolf",
    "bpv_status": 0,
    "ninja": 0,
    "x_shot_limit": 0,
    "strongman": 0,
    "janitor": 0,
    "even_night": 0,
    "odd_night": 0,
    "godfather": 0,
    "backup": 0,
    "night_x": 0,
    "recluse": 0,
    "vengeful": 0,
    "flipless": 0,
    "non_consecutive": 0,
    "self_targetable": 0,
    "powers": {
        "alignment inspection": 0,
        "fullcop": 0,
        "rolecop": 0,
        "bodyguard": 0,
        "protection": 0,
        "frame": 0,
        "jail": 0,
        "roleblock": 0,
        "track": 0,
        "watch": 0,
        "kill": 0
    },
    "ita_count": 0,
    "ita_base_hit": 0,
    "ita_immunity": 0,
    "ita_vulnerability": 0,
    "ita_shield_status": 0,
    "ita_booster": 0,
    "ita_nerfer": 0,
    "character_name": "",
    "character_image": "",
    "alignment": "wolf",
    "faction_color": "#ff2244"
}






