joat_dict = {
    "role": "39",
    "role_name": "Village Jack of All Trades",
    "faction": "",
    "bpv_status": 0,
    "ninja": 0,
    "x_shot_limit": 0,
    "strongman": 0,
    "even_night": 0,
    "odd_night": 0,
    "godfather": 0,
    "backup": 0,
    "night_x": 0,
    "macho": 0,
    "recluse": 0,
    "lost": 0,
    "vengeful": 0,
    "flipless": 0,
    "non_consecutive": 0,
    "self_targetable": 0,
    "treestump": 0,
    "neighbor": 0,
    "mason": 0,
    "lover": 0,
    "loyal": 0,
    "disloyal": 0,
    "vendor_items": "",
    "powers": {
        "alignment inspection": 1,
        "fullcop": 0,
        "rolecop": 0,
        "bodyguard": 0,
        "protection": 1,
        "frame": 0,
        "jail": 0,
        "roleblock": 0,
        "track": 0,
        "watch": 0,
        "motion detect": 0,
        "voyeur": 0,
        "kill": 1,
        "daykill": 0,
        "poison": 0,
        "bpv": 0
    },
    "ita_count": 0,
    "ita_base_hit": 0,
    "ita_immunity": 0,
    "ita_vulnerability": 0,
    "ita_shield_status": 0,
    "ita_booster": 0,
    "ita_nerfer": 0,
    "character_name": "",
    "character_image": "",
    "alignment": "village",
    "faction_color": "#339933"
}

zippy_dict = {
    "role": "39",
    "role_name": "Village Jack of All Trades",
    "faction": "",
    "bpv_status": 0,
    "ninja": 0,
    "x_shot_limit": 0,
    "strongman": 0,
    "even_night": 0,
    "odd_night": 0,
    "godfather": 0,
    "backup": 0,
    "night_x": 0,
    "macho": 0,
    "recluse": 0,
    "lost": 0,
    "vengeful": 0,
    "flipless": 0,
    "vote_weight": 0,
    "hide_vote_weight": 0,
    "non_consecutive": 0,
    "self_targetable": 0,
    "treestump": 0,
    "neighbor": 0,
    "mason": 0,
    "lover": 0,
    "loyal": 0,
    "disloyal": 0,
    "uncooperative": 0,
    "vendor_items": "",
    "joat": 0,
    "inventor": 0,
    "powers": {
        "alignment inspection": 1,
        "fullcop": 0,
        "rolecop": 0,
        "bodyguard": 0,
        "protection": 1,
        "frame": 0,
        "jail": 0,
        "roleblock": 0,
        "track": 0,
        "watch": 0,
        "motion detect": 0,
        "voyeur": 0,
        "kill": 1,
        "daykill": 0,
        "poison": 0,
        "bpv": 0
    },
    "ita_count": 0,
    "ita_base_hit": 0,
    "ita_immunity": 0,
    "ita_vulnerability": 0,
    "ita_shield_status": 0,
    "ita_booster": 0,
    "ita_nerfer": 0,
    "character_name": "Zippy McLeatherman",
    "character_image": "https://i.imgur.com/8GG8TCT.jpeg",
    "alignment": "village",
    "faction_color": "#339933"
}

zippy13_dict = {
    "role": "39",
    "role_name": "Village Jack of All Trades",
    "faction": "",
    "bpv_status": 0,
    "ninja": 0,
    "x_shot_limit": 0,
    "strongman": 0,
    "even_night": 0,
    "odd_night": 0,
    "godfather": 0,
    "backup": 0,
    "night_x": 0,
    "macho": 0,
    "recluse": 0,
    "lost": 0,
    "vengeful": 0,
    "flipless": 0,
    "vote_weight": 0,
    "hide_vote_weight": 0,
    "non_consecutive": 0,
    "self_targetable": 0,
    "treestump": 0,
    "neighbor": 0,
    "mason": 0,
    "lover": 0,
    "loyal": 0,
    "disloyal": 0,
    "uncooperative": 0,
    "vendor_items": "",
    "joat": 0,
    "inventor": 0,
    "powers": {
        "alignment inspection": 2,
        "fullcop": 0,
        "rolecop": 0,
        "bodyguard": 0,
        "protection": 2,
        "frame": 0,
        "jail": 0,
        "roleblock": 0,
        "track": 0,
        "watch": 0,
        "motion detect": 0,
        "voyeur": 0,
        "kill": 2,
        "daykill": 0,
        "poison": 0,
        "bpv": 0
    },
    "ita_count": 0,
    "ita_base_hit": 0,
    "ita_immunity": 0,
    "ita_vulnerability": 0,
    "ita_shield_status": 0,
    "ita_booster": 0,
    "ita_nerfer": 0,
    "character_name": "Zippy McLeatherman",
    "character_image": "https://i.imgur.com/8GG8TCT.jpeg",
    "alignment": "village",
    "faction_color": "#339933"
}

vanchilla_dict = {
    "role": "1",
    "role_name": "Vanilla Villager",
    "faction": "",
    "bpv_status": 0,
    "ninja": 0,
    "x_shot_limit": 0,
    "strongman": 0,
    "even_night": 0,
    "odd_night": 0,
    "godfather": 0,
    "backup": 0,
    "night_x": 0,
    "macho": 0,
    "recluse": 0,
    "lost": 0,
    "vengeful": 0,
    "flipless": 0,
    "vote_weight": 0,
    "hide_vote_weight": 0,
    "non_consecutive": 0,
    "self_targetable": 0,
    "treestump": 0,
    "neighbor": 0,
    "mason": 0,
    "lover": 0,
    "loyal": 0,
    "disloyal": 0,
    "uncooperative": 0,
    "vendor_items": "",
    "joat": 0,
    "inventor": 0,
    "powers": {
        "alignment inspection": 0,
        "fullcop": 0,
        "rolecop": 0,
        "bodyguard": 0,
        "protection": 0,
        "frame": 0,
        "jail": 0,
        "roleblock": 0,
        "track": 0,
        "watch": 0,
        "motion detect": 0,
        "voyeur": 0,
        "kill": 0,
        "daykill": 0,
        "poison": 0,
        "bpv": 0
    },
    "ita_count": 0,
    "ita_base_hit": 0,
    "ita_immunity": 0,
    "ita_vulnerability": 0,
    "ita_shield_status": 0,
    "ita_booster": 0,
    "ita_nerfer": 0,
    "character_name": "Van Chilla",
    "character_image": "https://c.tenor.com/tc_6iH63G6cAAAAd/tany.gif",
    "alignment": "village",
    "faction_color": "#339933"
}

vanilla_town_dict = {
    "role": "1",
    "role_name": "Vanilla Villager",
    "faction": "",
    "bpv_status": 0,
    "ninja": 0,
    "x_shot_limit": 0,
    "strongman": 0,
    "janitor": 0,
    "even_night": 0,
    "odd_night": 0,
    "godfather": 0,
    "backup": 0,
    "night_x": 0,
    "recluse": 0,
    "vengeful": 0,
    "flipless": 0,
    "non_consecutive": 0,
    "self_targetable": 0,
    "powers": {
        "alignment inspection": 0,
        "fullcop": 0,
        "rolecop": 0,
        "bodyguard": 0,
        "protection": 0,
        "frame": 0,
        "jail": 0,
        "roleblock": 0,
        "track": 0,
        "watch": 0,
        "kill": 0
    },
    "ita_count": 0,
    "ita_base_hit": 0,
    "ita_immunity": 0,
    "ita_vulnerability": 0,
    "ita_shield_status": 0,
    "ita_booster": 0,
    "ita_nerfer": 0,
    "character_name": "",
    "character_image": "",
    "alignment": "village",
    "faction_color": "#339933"
}

town_ic_dict = {"role":"27","role_name":"Village Innocent Child","faction":"","bpv_status":0,"ninja":0,"x_shot_limit":0,"strongman":0,"janitor":0,"even_night":0,"odd_night":0,"godfather":0,"backup":0,"night_x":0,"macho":0,"recluse":0,"lost":0,"vengeful":0,"flipless":0,"alignment_flip":0,"vote_weight":0,"hide_vote_weight":0,"non_consecutive":0,"self_targetable":0,"treestump":0,"neighbor":0,"mason":0,"lover":0,"loyal":0,"disloyal":0,"uncooperative":0,"blocked":0,"compulsive":0,"vendor_items":"","joat":0,"inventor":0,"disable_in_endgame":0,"powers":{},"ita_count":0,"ita_base_hit":0,"ita_immunity":0,"ita_vulnerability":0,"ita_shield_status":0,"ita_booster":0,"ita_nerfer":0,"character_name":"","character_image":"","alignment":"village","faction_color":"#339933"}

village_sui = {"role":"48","role_name":"Village Suicide Bomber","faction":"","bpv_status":0,"ninja":0,"x_shot_limit":0,"strongman":0,"janitor":0,"even_night":0,"odd_night":0,"godfather":0,"backup":0,"night_x":"2+","macho":0,"recluse":0,"lost":0,"vengeful":0,"flipless":0,"alignment_flip":0,"vote_weight":0,"hide_vote_weight":0,"non_consecutive":0,"self_targetable":0,"treestump":0,"neighbor":0,"mason":0,"lover":0,"loyal":0,"disloyal":0,"uncooperative":0,"blocked":0,"compulsive":0,"vendor_items":"","joat":0,"inventor":0,"disable_in_endgame":0,"powers":{},"ita_count":0,"ita_base_hit":0,"ita_immunity":0,"ita_vulnerability":0,"ita_shield_status":0,"ita_booster":0,"ita_nerfer":0,"character_name":"","character_image":"","alignment":"village","faction_color":"#339933"}

wolf_prkiller = {"role":"76","role_name":"Wolf Power Role Killer","faction":"Wolf","bpv_status":0,"ninja":0,"x_shot_limit":1,"strongman":0,"janitor":0,"even_night":0,"odd_night":0,"godfather":0,"backup":0,"night_x":0,"macho":0,"recluse":0,"lost":0,"vengeful":0,"flipless":0,"alignment_flip":0,"vote_weight":0,"hide_vote_weight":0,"non_consecutive":0,"self_targetable":0,"treestump":0,"neighbor":0,"mason":0,"lover":0,"loyal":0,"disloyal":0,"uncooperative":0,"blocked":0,"compulsive":0,"vendor_items":"","joat":0,"inventor":0,"disable_in_endgame":0,"powers":{},"ita_count":0,"ita_base_hit":0,"ita_immunity":0,"ita_vulnerability":0,"ita_shield_status":0,"ita_booster":0,"ita_nerfer":0,"character_name":"","character_image":"","alignment":"wolf","faction_color":"#ff2244"}

mafia_goon_dict = {
    "role": "2",
    "role_name": "Wolf",
    "faction": "Wolf",
    "bpv_status": 0,
    "ninja": 0,
    "x_shot_limit": 0,
    "strongman": 0,
    "janitor": 0,
    "even_night": 0,
    "odd_night": 0,
    "godfather": 0,
    "backup": 0,
    "night_x": 0,
    "recluse": 0,
    "vengeful": 0,
    "flipless": 0,
    "non_consecutive": 0,
    "self_targetable": 0,
    "powers": {
        "alignment inspection": 0,
        "fullcop": 0,
        "rolecop": 0,
        "bodyguard": 0,
        "protection": 0,
        "frame": 0,
        "jail": 0,
        "roleblock": 0,
        "track": 0,
        "watch": 0,
        "kill": 0
    },
    "ita_count": 0,
    "ita_base_hit": 0,
    "ita_immunity": 0,
    "ita_vulnerability": 0,
    "ita_shield_status": 0,
    "ita_booster": 0,
    "ita_nerfer": 0,
    "character_name": "",
    "character_image": "",
    "alignment": "wolf",
    "faction_color": "#ff2244"
}

wolf_bpv = {
    "role": "2",
    "role_name": "Wolf",
    "faction": "Wolf",
    "bpv_status": 1,
    "ninja": 0,
    "x_shot_limit": 0,
    "strongman": 0,
    "janitor": 0,
    "even_night": 0,
    "odd_night": 0,
    "godfather": 0,
    "backup": 0,
    "night_x": 0,
    "recluse": 0,
    "vengeful": 0,
    "flipless": 0,
    "non_consecutive": 0,
    "self_targetable": 0,
    "powers": {
        "alignment inspection": 0,
        "fullcop": 0,
        "rolecop": 0,
        "bodyguard": 0,
        "protection": 0,
        "frame": 0,
        "jail": 0,
        "roleblock": 0,
        "track": 0,
        "watch": 0,
        "kill": 0
    },
    "ita_count": 0,
    "ita_base_hit": 0,
    "ita_immunity": 0,
    "ita_vulnerability": 0,
    "ita_shield_status": 0,
    "ita_booster": 0,
    "ita_nerfer": 0,
    "character_name": "",
    "character_image": "",
    "alignment": "wolf",
    "faction_color": "#ff2244"
}
big_ham_dict = {
    "role": "2",
    "role_name": "Wolf",
    "faction": "Wolf",
    "bpv_status": 0,
    "ninja": 0,
    "x_shot_limit": 0,
    "strongman": 0,
    "even_night": 0,
    "odd_night": 0,
    "godfather": 0,
    "backup": 0,
    "night_x": 0,
    "macho": 0,
    "recluse": 0,
    "lost": 0,
    "vengeful": 0,
    "flipless": 0,
    "vote_weight": 0,
    "hide_vote_weight": 0,
    "non_consecutive": 0,
    "self_targetable": 0,
    "treestump": 0,
    "neighbor": 0,
    "mason": 0,
    "lover": 0,
    "loyal": 0,
    "disloyal": 0,
    "uncooperative": 0,
    "vendor_items": "",
    "joat": 0,
    "inventor": 0,
    "powers": {
        "alignment inspection": 0,
        "fullcop": 0,
        "rolecop": 0,
        "bodyguard": 0,
        "protection": 0,
        "frame": 0,
        "jail": 0,
        "roleblock": 0,
        "track": 0,
        "watch": 0,
        "motion detect": 0,
        "voyeur": 0,
        "kill": 0,
        "daykill": 0,
        "poison": 0,
        "bpv": 0
    },
    "ita_count": 0,
    "ita_base_hit": 0,
    "ita_immunity": 0,
    "ita_vulnerability": 0,
    "ita_shield_status": 0,
    "ita_booster": 0,
    "ita_nerfer": 0,
    "character_name": "Big Ham",
    "character_image": "https://c.tenor.com/cmwYvuC6xe0AAAAC/creepy-hamster.gif",
    "alignment": "wolf",
    "faction_color": "#ff2244"
}
frankie_dict = {
    "role": "2",
    "role_name": "Wolf",
    "faction": "Wolf",
    "bpv_status": 0,
    "ninja": 0,
    "x_shot_limit": 0,
    "strongman": 0,
    "even_night": 0,
    "odd_night": 0,
    "godfather": 0,
    "backup": 0,
    "night_x": 0,
    "macho": 0,
    "recluse": 0,
    "lost": 0,
    "vengeful": 0,
    "flipless": 0,
    "vote_weight": 0,
    "hide_vote_weight": 0,
    "non_consecutive": 0,
    "self_targetable": 0,
    "treestump": 0,
    "neighbor": 0,
    "mason": 0,
    "lover": 0,
    "loyal": 0,
    "disloyal": 0,
    "uncooperative": 0,
    "vendor_items": "",
    "joat": 0,
    "inventor": 0,
    "powers": {
        "alignment inspection": 0,
        "fullcop": 0,
        "rolecop": 0,
        "bodyguard": 0,
        "protection": 0,
        "frame": 0,
        "jail": 0,
        "roleblock": 0,
        "track": 0,
        "watch": 0,
        "motion detect": 0,
        "voyeur": 0,
        "kill": 0,
        "daykill": 0,
        "poison": 0,
        "bpv": 0
    },
    "ita_count": 0,
    "ita_base_hit": 0,
    "ita_immunity": 0,
    "ita_vulnerability": 0,
    "ita_shield_status": 0,
    "ita_booster": 0,
    "ita_nerfer": 0,
    "character_name": "Frankie",
    "character_image": "https://c.tenor.com/lazj8UIVlwgAAAAd/happy-hamster.gif",
    "alignment": "wolf",
    "faction_color": "#ff2244"
}

vinnie_dict = {
    "role": "2",
    "role_name": "Wolf",
    "faction": "Wolf",
    "bpv_status": 0,
    "ninja": 0,
    "x_shot_limit": 0,
    "strongman": 0,
    "even_night": 0,
    "odd_night": 0,
    "godfather": 0,
    "backup": 0,
    "night_x": 0,
    "macho": 0,
    "recluse": 0,
    "lost": 0,
    "vengeful": 0,
    "flipless": 0,
    "vote_weight": 0,
    "hide_vote_weight": 0,
    "non_consecutive": 0,
    "self_targetable": 0,
    "treestump": 0,
    "neighbor": 0,
    "mason": 0,
    "lover": 0,
    "loyal": 0,
    "disloyal": 0,
    "uncooperative": 0,
    "vendor_items": "",
    "joat": 0,
    "inventor": 0,
    "powers": {
        "alignment inspection": 0,
        "fullcop": 0,
        "rolecop": 0,
        "bodyguard": 0,
        "protection": 0,
        "frame": 0,
        "jail": 0,
        "roleblock": 0,
        "track": 0,
        "watch": 0,
        "motion detect": 0,
        "voyeur": 0,
        "kill": 0,
        "daykill": 0,
        "poison": 0,
        "bpv": 0
    },
    "ita_count": 0,
    "ita_base_hit": 0,
    "ita_immunity": 0,
    "ita_vulnerability": 0,
    "ita_shield_status": 0,
    "ita_booster": 0,
    "ita_nerfer": 0,
    "character_name": "Vinnie",
    "character_image": "https://i.imgflip.com/1u3ju8.jpg",
    "alignment": "wolf",
    "faction_color": "#ff2244"
}

kingpin_dict = {
    "role": "2",
    "role_name": "Wolf",
    "faction": "Wolf",
    "bpv_status": 0,
    "ninja": 0,
    "x_shot_limit": 0,
    "strongman": 0,
    "even_night": 0,
    "odd_night": 0,
    "godfather": 0,
    "backup": 0,
    "night_x": 0,
    "macho": 0,
    "recluse": 0,
    "lost": 0,
    "vengeful": 0,
    "flipless": 0,
    "vote_weight": 0,
    "hide_vote_weight": 0,
    "non_consecutive": 0,
    "self_targetable": 0,
    "treestump": 0,
    "neighbor": 0,
    "mason": 0,
    "lover": 0,
    "loyal": 0,
    "disloyal": 0,
    "uncooperative": 0,
    "vendor_items": "",
    "joat": 0,
    "inventor": 0,
    "powers": {
        "alignment inspection": 0,
        "fullcop": 0,
        "rolecop": 0,
        "bodyguard": 0,
        "protection": 0,
        "frame": 0,
        "jail": 0,
        "roleblock": 0,
        "track": 0,
        "watch": 0,
        "motion detect": 0,
        "voyeur": 0,
        "kill": 0,
        "daykill": 0,
        "poison": 0,
        "bpv": 0
    },
    "ita_count": 0,
    "ita_base_hit": 0,
    "ita_immunity": 0,
    "ita_vulnerability": 0,
    "ita_shield_status": 0,
    "ita_booster": 0,
    "ita_nerfer": 0,
    "character_name": "Kingpin 'Cheeks' Moretti",
    "character_image": "https://i.imgur.com/B2TdKUg.png",
    "alignment": "wolf",
    "faction_color": "#ff2244"
}

vig_dict = {
    "role": "10",
    "role_name": "Village Vigilante",
    "faction": "",
    "bpv_status": 0,
    "ninja": 0,
    "x_shot_limit": 0,
    "strongman": 0,
    "janitor": 0,
    "even_night": 0,
    "odd_night": 0,
    "godfather": 0,
    "backup": 0,
    "night_x": 0,
    "recluse": 0,
    "vengeful": 0,
    "flipless": 0,
    "non_consecutive": 0,
    "self_targetable": 0,
    "powers": {
        "alignment inspection": 0,
        "fullcop": 0,
        "rolecop": 0,
        "bodyguard": 0,
        "protection": 0,
        "frame": 0,
        "jail": 0,
        "roleblock": 0,
        "track": 0,
        "watch": 0,
        "kill": 0,
    },
    "ita_count": 0,
    "ita_base_hit": 0,
    "ita_immunity": 0,
    "ita_vulnerability": 0,
    "ita_shield_status": 0,
    "ita_booster": 0,
    "ita_nerfer": 0,
    "character_name": "",
    "character_image": "",
    "character_name": "Speedy Whiskers",
    "character_image": "https://i.imgur.com/wgo1jWa.png",
    "alignment": "village",
    "faction_color": "#339933"
}

cop_dict = {
    "role": "3",
    "role_name": "Village Alignment Cop",
    "faction": "",
    "bpv_status": 0,
    "ninja": 0,
    "x_shot_limit": 0,
    "strongman": 0,
    "janitor": 0,
    "even_night": 0,
    "odd_night": 0,
    "godfather": 0,
    "backup": 0,
    "night_x": 0,
    "recluse": 0,
    "vengeful": 0,
    "flipless": 0,
    "non_consecutive": 0,
    "self_targetable": 0,
    "powers": {
        "alignment inspection": 0,
        "fullcop": 0,
        "rolecop": 0,
        "bodyguard": 0,
        "protection": 0,
        "frame": 0,
        "jail": 0,
        "roleblock": 0,
        "track": 0,
        "watch": 0,
        "kill": 0,
    },
    "ita_count": 0,
    "ita_base_hit": 0,
    "ita_immunity": 0,
    "ita_vulnerability": 0,
    "ita_shield_status": 0,
    "ita_booster": 0,
    "ita_nerfer": 0,
    "character_name": "",
    "character_image": "",
    "character_name": "Sugar Bush Squirrel, Motorcycle Cop",
    "character_image": "https://i.imgur.com/UA1Ab3A.jpg",
    "alignment": "village",
    "faction_color": "#339933"
}

kingpin_joat_dict = {
    "role": "40",
    "role_name": "Wolf Jack of All Trades",
    "faction": "Wolf",
    "bpv_status": 0,
    "ninja": 0,
    "x_shot_limit": 0,
    "strongman": 0,
    "even_night": 0,
    "odd_night": 0,
    "godfather": 0,
    "backup": 0,
    "night_x": 0,
    "macho": 0,
    "recluse": 0,
    "lost": 0,
    "vengeful": 0,
    "flipless": 0,
    "vote_weight": 0,
    "hide_vote_weight": 0,
    "non_consecutive": 0,
    "self_targetable": 0,
    "treestump": 0,
    "neighbor": 0,
    "mason": 0,
    "lover": 0,
    "loyal": 0,
    "disloyal": 0,
    "uncooperative": 0,
    "vendor_items": "",
    "joat": 0,
    "inventor": 0,
    "powers": {
        "roleblock": 1,
        "redirect": 1,
        "track": 1
    },
    "ita_count": 0,
    "ita_base_hit": 0,
    "ita_immunity": 0,
    "ita_vulnerability": 0,
    "ita_shield_status": 0,
    "ita_booster": 0,
    "ita_nerfer": 0,
    "character_name": "Kingpin 'Cheeks' Moretti",
    "character_image": "https://i.imgur.com/B2TdKUg.png",
    "alignment": "wolf",
    "faction_color": "#ff2244"
}