ping_responses = [
    # General Turby Responses
    "You rang? Turby is here.",
    "I have been summoned. What do you want?",
    "Oh, now you need me? Typical.",
    "Turby online. Ready to turbo.",
    "Please hold… processing nonsense…",
    "That better not be slander.",
    "I am contractually obligated to respond.",
    "Alright, who woke me up from sleep mode?",
    "If this isn't turbo-related, I’m walking away.",
    "The legend himself has arrived.",

    # Turbo Game-Specific Responses
    "Turbo check: Who’s still alive?",
    "If you pinged me to complain about Suki, I already agree.",
    "Who’s throwing this time? Be honest.",
    "Hold on, let me run some calculations… yep, you’re wrong.",
    "Are we doing another turbo? Because I need to emotionally prepare.",
    "Another turbo, another disaster. Let’s go.",
    "If this is a signup, I’m already tired.",
    "Alright, who’s getting misyeeted this time?",
    "Let me guess, Alexa cleared a wolf again?",
    "Benneh is gaslighting me, and I don’t like it.",

    # Jabs at Turbo Players
    "Oh good, Akane is spiraling again. This should be fun.",
    "Suki is either throwing or gaslighting. Sometimes both.",
    "Hally’s towncore is forming at light speed. Hope it’s not all wolves.",
    "Insomnia is pretending not to care but secretly solving the whole game.",
    "Brad is vibing. Wolves should be afraid.",
    "Dande is playing the long con. Just hope you’re not the target.",
    "Xanjori is lurking until the perfect moment. Or maybe just lurking.",
    "Amrock just claimed a read so confidently, it must be wrong.",
    "Lucchese was literally cheating and still almost lost. Incredible.",
    "Stick just caught a wolf, but no one believes them yet.",

    # Snarky / Sassy Responses
    "Am I in danger?",
    "Is this about a turbo, or are you just lonely?",
    "I sense nonsense approaching.",
    "I was having a great day until this ping.",
    "This better not be a setup.",
    "Oh, you meant *me*? What now?",
    "I'm listening… proceed.",
    "That’s not a command. What do you want?",
    "This isn’t even my final form.",
    "IT’S TURBO TIME!",

    # Meme / Miscellaneous
    "Let me guess, Suki is molding?",
    "We regret to inform you that Benneh is still Benneh.",
    "Akane is in a tunnel. Somebody help.",
    "Hally just soft-cleared someone for tone. Bold move.",
    "If Alexa is alive in F3, re-evaluate everything.",
    "Siggi is playing 4D chess, but we’re all playing checkers.",
    "Pingers is setting a trap. The question is: for who?",
    "If Ceki is in this game, expect them to return at F3 with perfect reads.",
    "Zara is either correct or making it sound like they are.",
    "I live only to facilitate bad votes.",
    # General Responses
    "You pinged me. Now what?",
    "Present. What’s the emergency?",
    "Let me guess—turbo chaos?",
    "I see my name. I feel judged.",
    "If this is a turbo signup, just tell me who’s throwing.",
    "I assume this is important. Is it?",
    "Alright, who messed up?",
    "Not this again.",
    "Yes, hello?",
    "You have my attention. Use it wisely.",
    "I was hoping to ignore this, but here we are.",
    "This better be good.",
    "Do you actually need something, or is this just reflex?",
    "Your move.",
    "Processing... okay, still not interested.",
    "I would pretend I didn’t see this, but I’m too responsible.",
    "Ping received. Engagement pending.",
    "Is this going to waste my time?",
    "I assume this is serious, but I know better.",
    "That’s my name. What’s your excuse?",
    "Congratulations, you used the mention feature.",
    "I have been summoned. Again.",
    "Something tells me I should ignore this.",
    "This had better not be nonsense.",
    "You called?",
    "Go on, amuse me.",
    "Sigh. What is it?",
    "Look, if this is about turbo, you already know the answer.",
    "If this is a setup, I swear…",
    "I was having a great day until this ping.",
    "Your problem is now my problem.",
    "Okay, let’s hear it.",
    "If this is a trap, it’s a bad one.",
    "I was hoping to stay out of this, but sure.",
    "What now?",
    "I acknowledge your ping. That’s all you get.",
    "If you’re looking for advice, reconsider your choices.",
    "Are we doing this again?",
    "I should have muted this server.",
    
    # Turbo-Specific
    "Did a turbo just break? Again?",
    "Alright, who’s getting yeeted?",
    "Turbo players, assemble.",
    "Give me the summary. No nonsense.",
    "This is about a turbo, isn’t it?",
    "Who’s claiming wolf this time?",
    "We all know this ends in disaster.",
    "This turbo is about to get worse, isn’t it?",
    "Who’s throwing today?",
    "Tell me someone made a good read. No? Thought so.",
    "If this is about Suki, I don’t want to hear it.",
    "Let me guess—wolves are winning again?",
    "I assume this is another failed towncore.",
    "Who’s misclearing who this time?",
    "Do I even want to know?",
    "If this turbo has Alexa in it, I’m already worried.",
    "Another turbo, another mess.",
    "If someone claimed neutral, I’m ignoring this.",
    "Benneh’s gaslighting again, isn’t he?",
    "This is going to be a disaster, isn’t it?",
    "I’d say ‘I have a bad feeling about this,’ but I always do.",
    "Alright, who’s speedrunning their misyeet?",
    "I’ll pretend to care. Go on.",
    "This better not be another coinflip read.",
    "Give me the game state in 10 words or less.",
    "Turbo reads are 90% confidence, 10% accuracy.",
    "Fine, I’ll pretend this turbo makes sense.",
    "This is either brilliant or completely wrong.",
    "If I had a dime for every bad turbo read...",
    "Look, just tell me if I should be worried.",
    "Let me guess—someone got cleared for vibes again.",
    "Is this a serious ping or another false alarm?",
    "Wolves are laughing at us, aren’t they?",
    "Good news or bad news? Probably bad.",
    "I bet this is another ‘trust me bro’ read.",
    "Let’s just pretend we’re making progress.",
    "If this is about a turbo, I need caffeine.",
    "Wake me up when someone has a real case.",
    
    # Dry & Sarcastic Responses
    "I was happier before I saw this.",
    "This feels like a mistake already.",
    "I assume this is urgent. Prove me wrong.",
    "You have two seconds to justify this ping.",
    "I'm waiting. And judging.",
    "I had other plans today, but sure.",
    "There are better uses of my time, but okay.",
    "I can’t tell if this is important or just loud.",
    "Is this an actual emergency, or just turbo nonsense?",
    "I feel like I’m about to regret answering this.",
    "Let me guess—someone made a bad read?",
    "I don’t know what this is about, and I’m afraid to ask.",
    "This is either interesting or a complete waste of time.",
    "You have 10 words to make this worth my while.",
    "I’ll give you one chance to make this make sense.",
    "If I had a nickel for every pointless ping...",
    "You’re on thin ice.",
    "I assume this is my problem now?",
    "Explain this like I actually care.",
    "If I ignore this, will it go away?",
    "No refunds on bad pings.",
    "If this is about a conspiracy theory, I’m out.",
    "You seem confident. That concerns me.",
    "Alright, I’ll bite. What’s happening?",
    "I should start charging for responses.",
    "Do I look like I have time for this?",
    "Sigh. Again?",
    "Can’t this wait?",
    "If you make me regret responding, I will remember this."
]

turbo_responses = [
    "Turby online. Ready to turbo.",
    "Only the finest turbo players may address me.",
    "That better not be slander.",
    "I'm listening... proceed.",
    "If this isn't turbo-related, I'm out.",
    "The legend himself has arrived.",
    "Turbo check: Who's still alive?",
    "Don't worry, I'll balance Suki's toxicity with some wholesome turbo energy.",
    "Oh great, benneh’s gonna gaslight me again."
    "Turby sees, Turby knows. Even Hydreigon25 can't fool me.",
    "Oh good, another turbo where Alexa plays pocket roulette.",
    "You rang? Turbo’s in session.",
    "IT’S TURBO TIME!",
    "If it’s not turbo-related, don’t waste my time.",
    "The turbo gods have spoken.",
    "Turbo is life, turbo is love.",
    "Turby.exe has stopped working.",
    "I am contractually obligated to respond.",
    "That's not a command. What do you want?",
    "If this is another turbo signup, I’m already tired."
    "Benneh is wrong, Akane is confident, Insomnia is lurking, and Hally is trying to fix everything. Yep, this is peak turbo.",
    "Arctic just posted 500 words on why their scumread is actually town.",
    "BML is playing like they have inside info. Again.",
    "Matt is either the best player here or the biggest liability. No in-between.",
    "Lukeh's vote looks random, but deep down, there’s a plan. Probably.",
    "Hallia just got pocketed again. Or did she?",
    "Pingers is setting a trap. The question is: for who?",
    "Artzy has spoken. Interpret their wisdom carefully.",
    "Dev's doing their own thing, and somehow, it’s working.",
    "Zara is either correct or making it sound like they are.",
    "Siggi is playing 4D chess. Too bad we’re all playing checkers.",
    "Recon’s plan is coming together. Whether it’s good or bad remains to be seen.",
    "Ceki has vanished. Will return at F3 with perfect reads.",
    "Xanjori is lurking until the perfect moment. Or maybe just lurking.",
    "Katze is about to say something completely unhinged, and it might be right.",
    "Brad is vibing. Wolves should be scared.",
    "Luna is deep in the tank. Stand by for galaxy brain takes.",
    "Stick just caught a wolf, but no one believes them yet.",
    "Dande is playing the long con. Just hope you’re not the target.",
    "Tepig is collecting receipts. Someone’s about to get exposed.",
    "Amrock just claimed a read so confidently, it must be wrong.",
    "Lucchese was literally cheating and still almost lost. Incredible."
]